In [1]:
import pandas as pd
from plotnine import *

bio_raw = pd.read_csv ("./data/bio-raw.csv")

bio_raw

,_id,area_code,lower_uncertainty,scenario,upper_uncertainty,value,variable,year
0,344002,001-002-202-018-BWA,NaN,ssp4rcp6p0gcam,NaN,0.759763,bii,2044
1,344003,001-002-202-018-LSO,NaN,ssp4rcp6p0gcam,NaN,0.553173,bii,2044
2,344006,001-002-202-018-ZAF,NaN,ssp4rcp6p0gcam,NaN,0.623727,bii,2044
3,344014,001-009-054-PNG,NaN,ssp4rcp6p0gcam,NaN,0.986023,bii,2044
4,344023,001-009-057-PLW,NaN,ssp4rcp6p0gcam,NaN,NaN,bii,2044
...,...,...,...,...,...,...,...,...
376987,678732,001-150-154-ISL,NaN,ssp5rcp8p5remindmagpie,NaN,0.001034,urbanextent,2050
376988,678736,001-150-154-SJM,NaN,ssp5rcp8p5remindmagpie,NaN,0.000145,urbanextent,2050
376989,678741,001-150-155-DEU,NaN,ssp5rcp8p5remindmagpie,NaN,0.051676,urbanextent,2050
376990,678744,001-150-155-LUX,NaN,ssp5rcp8p5remindmagpie,NaN,0.113514,urbanextent,2050
376991,678747,NaN,NaN,ssp5rcp8p5remindmagpie,NaN,0.059755,urbanextent,2050

In [2]:
#| set index as year | sorted index in year order | selected years 2003 to 2013 |#

bio_year = bio_raw.set_index ('year') .sort_index ( ) .loc ['2003' : '2013']

bio_year

,_id,area_code,lower_uncertainty,scenario,upper_uncertainty,value,variable
year,,,,,,,
2003,411111,001-019-419-013,NaN,historical,NaN,0.067027,highintensityag
2003,519014,001-142-143-TKM,NaN,historical,NaN,0.695332,pastureland
2003,519010,001-142-035-VNM,NaN,historical,NaN,0.021656,pastureland
2003,518993,001-142-034-BTN,NaN,historical,NaN,0.112373,pastureland
2003,303593,001-142-145-ARM,NaN,historical,NaN,0.748149,bii
...,...,...,...,...,...,...,...
2013,521565,001-002-015-ESH,NaN,historical,NaN,0.181604,pastureland
2013,306206,001-009-054-PNG,NaN,historical,NaN,0.979433,bii
2013,306362,001-150-154-IMN,NaN,historical,NaN,0.558573,bii
2013,629420,001-142-030-MAC,NaN,historical,NaN,0.062490,urbanextent
2013,306351,001-150-151-RUS,NaN,historical,NaN,0.881639,bii

In [3]:
#| selecting only historical data for accuracy |#

bio_hist = bio_year [bio_year ["scenario"] == "historical"]

bio_hist

,_id,area_code,lower_uncertainty,scenario,upper_uncertainty,value,variable
year,,,,,,,
2003,411111,001-019-419-013,NaN,historical,NaN,0.067027,highintensityag
2003,519014,001-142-143-TKM,NaN,historical,NaN,0.695332,pastureland
2003,519010,001-142-035-VNM,NaN,historical,NaN,0.021656,pastureland
2003,518993,001-142-034-BTN,NaN,historical,NaN,0.112373,pastureland
2003,303593,001-142-145-ARM,NaN,historical,NaN,0.748149,bii
...,...,...,...,...,...,...,...
2013,521565,001-002-015-ESH,NaN,historical,NaN,0.181604,pastureland
2013,306206,001-009-054-PNG,NaN,historical,NaN,0.979433,bii
2013,306362,001-150-154-IMN,NaN,historical,NaN,0.558573,bii
2013,629420,001-142-030-MAC,NaN,historical,NaN,0.062490,urbanextent
2013,306351,001-150-151-RUS,NaN,historical,NaN,0.881639,bii

In [4]:
#| selects for variable method "high intensity agriculture" for consistant, reliable and relivant value ranges |#

bio_hiag = bio_hist [bio_hist ["variable"] == "highintensityag"]

bio_hiag

,_id,area_code,lower_uncertainty,scenario,upper_uncertainty,value,variable
year,,,,,,,
2003,411111,001-019-419-013,NaN,historical,NaN,0.067027,highintensityag
2003,411110,001-019-419-005,NaN,historical,NaN,0.061261,highintensityag
2003,411114,001-002-015,NaN,historical,NaN,0.052804,highintensityag
2003,411117,001-009-054,NaN,historical,NaN,0.003778,highintensityag
2003,411122,001-142-030,NaN,historical,NaN,0.132414,highintensityag
...,...,...,...,...,...,...,...
2013,413967,001-019-419-029-AIA,NaN,historical,NaN,NaN,highintensityag
2013,413973,001-019-419-029-CUW,NaN,historical,NaN,0.024709,highintensityag
2013,414008,001-142-035-BRN,NaN,historical,NaN,0.013005,highintensityag
2013,414011,001-142-035-LAO,NaN,historical,NaN,0.036629,highintensityag
2013,414014,001-142-035-PHL,NaN,historical,NaN,0.185763,highintensityag

In [5]:
#| removing null value outputs |#

bio_val = bio_hiag [bio_hiag ["value"] >= 0]

bio_val

,_id,area_code,lower_uncertainty,scenario,upper_uncertainty,value,variable
year,,,,,,,
2003,411111,001-019-419-013,NaN,historical,NaN,0.067027,highintensityag
2003,411110,001-019-419-005,NaN,historical,NaN,0.061261,highintensityag
2003,411114,001-002-015,NaN,historical,NaN,0.052804,highintensityag
2003,411117,001-009-054,NaN,historical,NaN,0.003778,highintensityag
2003,411122,001-142-030,NaN,historical,NaN,0.132414,highintensityag
...,...,...,...,...,...,...,...
2013,413941,001-019-021-USA,NaN,historical,NaN,0.146066,highintensityag
2013,413973,001-019-419-029-CUW,NaN,historical,NaN,0.024709,highintensityag
2013,414008,001-142-035-BRN,NaN,historical,NaN,0.013005,highintensityag
2013,414011,001-142-035-LAO,NaN,historical,NaN,0.036629,highintensityag
2013,414014,001-142-035-PHL,NaN,historical,NaN,0.185763,highintensityag

In [6]:
bio_sort = bio_val.drop (columns = ["_id", "lower_uncertainty", "scenario", "upper_uncertainty", "variable"])

bio_sort

                area_code     value
year
2003      001-019-419-013  0.067027
2003      001-019-419-005  0.061261
2003          001-002-015  0.052804
2003          001-009-054  0.003778
2003          001-142-030  0.132414
...                   ...       ...
2013      001-019-021-USA  0.146066
2013  001-019-419-029-CUW  0.024709
2013      001-142-035-BRN  0.013005
2013      001-142-035-LAO  0.036629
2013      001-142-035-PHL  0.185763

[2541 rows x 2 columns]